---
abstract: 'Perl module to calculate the speed of sound in pure water and sea water'
author:
  - 'Steven Troxel < steven.troxel@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Physics-Water-SoundSpeed
no_index:
  directory:
    - t
    - inc
requires: {}
version: 0.92
